services:
  itrum-wallet-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: itrum-wallet-app
    ports:
      - "${APP_PORT:-8080}:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/${POSTGRES_DB:-itrumwallet}
      DB_USER: ${POSTGRES_USER:-postgres}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      SERVER_PORT: 8080
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - itrum-wallet-network

  db:
    image: postgres:18.2-alpine3.22
    container_name: itrum-wallet-postgres
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-itrumwallet}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
        - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-itrumwallet}"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    networks:
      - itrum-wallet-network

networks:
  itrum-wallet-network:
    driver: bridge

volumes:
  postgres_data:
    name: itrum-wallet-postgres-data

